[package]
name = "smol_str"
version = "0.1.2"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/smol_str"
description = "small-string optimized stirng type with O(1) clone"
license = "MIT OR Apache-2.0"

[dev-dependencies]
proptest = "0.8.3"
